"""AI agent that retrieves census data for a country and explains it with Llama 3.1.

Type a country name and the agent gathers:
  - GDP (current US$)            -- World Bank public API
  - Total population             -- World Bank public API
  - Population density           -- World Bank public API
  - Religions followed           -- CIA World Factbook (factbook.json mirror)

then has `meta/llama-3.1-8b-instruct` (via NVIDIA's OpenAI-compatible API at
https://integrate.api.nvidia.com) write a short plain-language explanation of
what the figures say about the country.

Run:
    pip install -r requirements.txt
    cp .env.example .env   # then fill in NVIDIA_API_KEY (free at build.nvidia.com)
    python census_agent.py           # interactive prompt
    python census_agent.py France    # or pass the country as an argument

Country-name resolution (e.g. "uk" -> United Kingdom, "south korea" -> Korea,
Republic of) runs fully offline via the bundled `pycountry` ISO-3166 database.
The World Bank and Factbook lookups need network access but no API key; only
the Llama explanation step needs NVIDIA_API_KEY. If the key is missing or the
model call fails, the retrieved data is still printed -- you just lose the
explanation paragraph.
"""

import json
import os
import sys
from pathlib import Path

import agenthog
import httpx
import pycountry
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# Optional AgentHog tracing (theagentos.space -- same service app.py reports
# to). Activates only when both AGENTOS_API_KEY and AGENTOS_WORKSPACE_ID are
# set; without them the agent runs exactly as before and nothing is sent
# anywhere. See .env.example.
_TRACING_ENABLED = bool(os.getenv("AGENTOS_API_KEY")) and bool(os.getenv("AGENTOS_WORKSPACE_ID"))
if _TRACING_ENABLED:
    agenthog.init(
        api_key=os.environ["AGENTOS_API_KEY"],
        endpoint=os.environ.get("AGENTOS_ENDPOINT", "https://api.theagentos.space"),
        workspace_id=os.environ["AGENTOS_WORKSPACE_ID"],
        agent_id="census-data-agent",
    )
    # Patches the openai client used in explain(); on agenthog >= 0.6.0 this
    # also captures raw-HTTP OpenAI-compatible calls made via httpx/requests.
    agenthog.autoinstrument()
elif bool(os.getenv("AGENTOS_API_KEY")) != bool(os.getenv("AGENTOS_WORKSPACE_ID")):
    print(
        "AgentHog tracing NOT enabled: set both AGENTOS_API_KEY and "
        "AGENTOS_WORKSPACE_ID (one is missing). See .env.example.",
        file=sys.stderr,
    )

MODEL = "meta/llama-3.1-8b-instruct"
# NVIDIA's hosted NIM endpoint serves this model behind an OpenAI-compatible
# API. Point LLM_BASE_URL elsewhere (e.g. a local NIM or vLLM server) to swap
# providers without touching the code.
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://integrate.api.nvidia.com/v1")

WORLD_BANK_BASE = "https://api.worldbank.org/v2"
FACTBOOK_RAW_BASE = "https://raw.githubusercontent.com/factbook/factbook.json/master"
# ISO alpha-3 -> Factbook file location, generated by scripts/build_factbook_index.py.
FACTBOOK_INDEX_PATH = Path(__file__).resolve().parent / "data" / "factbook_index.json"

# World Bank indicator codes -- see https://data.worldbank.org/indicator
INDICATORS = {
    "gdp_current_usd": "NY.GDP.MKTP.CD",
    "total_population": "SP.POP.TOTL",
    "population_density_per_sq_km": "EN.POP.DNST",
}


@agenthog.tool(name="resolve_country")
def _resolve_country(name: str) -> tuple[str, str]:
    """Resolve a user-typed country name to (iso3_code, official_name). Offline."""
    try:
        match = pycountry.countries.lookup(name)
    except LookupError:
        matches = pycountry.countries.search_fuzzy(name)
        match = matches[0]
    return match.alpha_3, match.name


@agenthog.tool(name="fetch_world_bank_indicator")
def _fetch_indicator(iso3: str, indicator_code: str) -> dict | None:
    """Fetch the most recent non-empty value for one World Bank indicator."""
    url = f"{WORLD_BANK_BASE}/country/{iso3}/indicator/{indicator_code}"
    params = {"format": "json", "per_page": 1, "mrnev": 1}
    response = httpx.get(url, params=params, timeout=10.0)
    response.raise_for_status()
    payload = response.json()
    if len(payload) < 2 or not payload[1]:
        return None
    record = payload[1][0]
    if record.get("value") is None:
        return None
    return {"year": record["date"], "value": record["value"]}


@agenthog.tool(name="fetch_factbook_religions")
def _fetch_religions(iso3: str) -> str | None:
    """Fetch the religion breakdown for a country from the CIA World Factbook."""
    index = json.loads(FACTBOOK_INDEX_PATH.read_text())
    entry = index.get(iso3)
    if entry is None:
        return None
    url = f"{FACTBOOK_RAW_BASE}/{entry['region']}/{entry['gec']}.json"
    response = httpx.get(url, timeout=15.0, follow_redirects=True)
    response.raise_for_status()
    religions = response.json().get("People and Society", {}).get("Religions", {})
    return religions.get("text")


def _humanize_usd(value: float) -> str:
    for threshold, unit in ((1e12, "trillion"), (1e9, "billion"), (1e6, "million")):
        if abs(value) >= threshold:
            return f"${value / threshold:,.2f} {unit}"
    return f"${value:,.0f}"


def get_census_data(country: str) -> tuple[str | None, str]:
    """Retrieve GDP, population, density, and religions for a country.

    Returns (official_name, report). official_name is None when the country
    couldn't be resolved, in which case the report is the error message.
    """
    try:
        iso3, official_name = _resolve_country(country)
    except LookupError:
        return None, f"Could not find a country matching '{country}'. Please check the spelling."

    lines = [f"Country: {official_name} ({iso3})"]

    presentation = {
        "gdp_current_usd": ("GDP (current US$)", _humanize_usd),
        "total_population": ("Total Population", lambda v: f"{v:,.0f} people"),
        "population_density_per_sq_km": (
            "Population Density",
            lambda v: f"{v:,.1f} people per sq km",
        ),
    }
    for label, code in INDICATORS.items():
        pretty_label, format_value = presentation[label]
        try:
            data = _fetch_indicator(iso3, code)
        except httpx.HTTPError as exc:
            lines.append(f"{pretty_label}: lookup failed ({exc})")
            continue
        if data is None:
            lines.append(f"{pretty_label}: data unavailable")
        else:
            lines.append(f"{pretty_label} ({data['year']}): {format_value(data['value'])}")

    try:
        religions = _fetch_religions(iso3)
    except (httpx.HTTPError, OSError, ValueError) as exc:
        religions = None
        lines.append(f"Religions: lookup failed ({exc})")
    else:
        lines.append(f"Religions: {religions}" if religions else "Religions: data unavailable")

    return official_name, "\n".join(lines)


def explain(report: str) -> str:
    """Have meta/llama-3.1-8b-instruct write a short explanation of the data."""
    api_key = os.getenv("NVIDIA_API_KEY")
    if not api_key:
        return (
            "(Skipping the AI explanation: NVIDIA_API_KEY is not set. Copy "
            ".env.example to .env and add a key from https://build.nvidia.com "
            "to enable it.)"
        )
    client = OpenAI(base_url=LLM_BASE_URL, api_key=api_key)
    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a concise demographics and economics analyst. You are "
                    "given verified census data for one country. Explain what the "
                    "figures say about the country in one short paragraph (4-6 "
                    "sentences): the size of its economy, how populous and how "
                    "densely settled it is, and its religious makeup. Base the "
                    "explanation only on the data provided; if a figure is marked "
                    "unavailable, say so rather than guessing."
                ),
            },
            {"role": "user", "content": report},
        ],
        temperature=0.3,
        max_tokens=400,
    )
    return completion.choices[0].message.content.strip()


def run_agent(country: str) -> str:
    """Retrieve the census data for one country, then explain it. Returns full output.

    One call = one task_run in AgentHog: the tool steps (country resolution,
    World Bank + Factbook lookups) and the Llama explanation call all nest
    under it. A no-op when tracing isn't configured.
    """
    with agenthog.start_task_run(agent_id="census-data-agent"):
        return _run_agent_inner(country)


def _run_agent_inner(country: str) -> str:
    official_name, report = get_census_data(country)
    if official_name is None:
        return report

    sections = ["=" * 60, report, "=" * 60]
    try:
        sections += ["", explain(report)]
    except Exception as exc:  # the data is still useful if the LLM call fails
        sections += ["", f"(AI explanation failed: {exc})"]
    return "\n".join(sections)


def main() -> None:
    if len(sys.argv) > 1:
        print(run_agent(" ".join(sys.argv[1:]).strip()))
        return
    while True:
        try:
            country = input("Enter a country name (blank to quit): ").strip()
        except EOFError:
            return
        if not country:
            return
        print(run_agent(country))
        print()


if __name__ == "__main__":
    main()
